If any step in the build process fails, don't continue to the next targets

diff --git a/build b/build
--- a/build
+++ b/build
@@ -26,9 +26,24 @@ install() {
 
 . $1
 (
-	fetch || echo "Failed to fetch $1" >> $top/morpheus.log
-	unpack || echo "Failed to unpack $1" >> $top/morpheus.log
-	patch || echo "Failed to patch $1" >> $top/morpheus.log
-	build || echo "Failed to build $1" >> $top/morpheus.log
-	install || echo "Failed to install $1" >> $top/morpheus.log
+	if ! fetch; then
+		echo "Failed to fetch $1" >> $top/morpheus.log
+		exit 1
+	fi
+	if ! unpack; then
+		echo "Failed to unpack $1" >> $top/morpheus.log
+		exit 1
+	fi
+	if ! patch; then
+		echo "Failed to patch $1" >> $top/morpheus.log
+		exit 1
+	fi
+	if ! build; then
+		echo "Failed to build $1" >> $top/morpheus.log
+		exit 1
+	fi
+	if ! install; then
+		echo "Failed to install $1" >> $top/morpheus.log
+		exit 1
+	fi
 )
